version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on: 
      - database
    
  database:
    image: postgres:latest
    container_name: database
    environment:
        - POSTGRES_DB=cleaning
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    volumes:
        - ./.containers/cleaning-db:/var/lib/postgresql/data
    ports:
        - 5432:5432